# Generated by Django 4.0.2 on 2022-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.IntegerField(verbose_name='control_number')),
                ('lastName', models.CharField(max_length=100, verbose_name='lastName')),
                ('firstName', models.CharField(max_length=150, verbose_name='firstName')),
                ('middleName', models.CharField(max_length=100, verbose_name='middleName')),
                ('suffix', models.CharField(max_length=5, verbose_name='suffix')),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('sex', models.CharField(max_length=6, verbose_name='sex')),
                ('status', models.CharField(max_length=30, verbose_name='status')),
                ('course', models.CharField(max_length=100, verbose_name='course')),
                ('strand', models.CharField(max_length=100, verbose_name='strand')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
