# Generated by Django 4.0.2 on 2022-02-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicant',
            table='ApplicantInfoTable',
        ),
    ]
