# Generated by Django 4.0.1 on 2022-02-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApp', '0001_initial'),
    ]

    operations = [
    ]
