# Generated by Django 4.0.2 on 2022-04-09 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_result', models.CharField(blank=True, max_length=6)),
                ('medical_file', models.FileField(blank=True, null=True, upload_to='')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=30)),
                ('interviewer', models.CharField(blank=True, max_length=100)),
                ('interview_result', models.CharField(blank=True, max_length=6)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntranceExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=30)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('time_taken', models.TimeField(blank=True, null=True)),
                ('time_finished', models.TimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('exam_result', models.CharField(blank=True, max_length=6)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shs_card', models.BooleanField(default=False)),
                ('good_moral_char', models.BooleanField(default=False)),
                ('brgy_clearance', models.BooleanField(default=False)),
                ('birth_cert', models.BooleanField(default=False)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('shs_strand', models.CharField(max_length=50)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
