# Generated by Django 4.0.2 on 2022-04-27 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='applicantrequirements',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entranceexamresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicalresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantrequirements',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entranceexamresult',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
