# Generated by Django 4.0.2 on 2022-05-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_medicalresult_medical_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalresult',
            name='medical_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
