# Generated by Django 4.0 on 2022-05-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='valid_start',
        ),
    ]
