# Generated by Django 4.0 on 2022-05-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_verification_valid_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='valid_end',
            new_name='valid_until',
        ),
    ]
