# Generated by Django 4.0.2 on 2022-04-23 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_interviewresult_applicant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
