# Generated by Django 4.0 on 2022-06-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_valid_end_verification_valid_until'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
